/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package WorkAreas.FacultyRole;

import Business.Business;
import Business.Profiles.FacultyProfile;
import WorkAreas.AdminRole.PersonRegistrationJPanel;
import javax.swing.JPanel;

/**
 *
 * @author kal
 */
public class FacultyWorkAreaJPanel extends javax.swing.JPanel {

    javax.swing.JPanel CardSequencePanel;
    Business business;
    FacultyProfile faculty;

    /**
     * Creates new form UnitRiskWorkArea
     */

    public FacultyWorkAreaJPanel(Business b, FacultyProfile fp, JPanel clp) {

        business = b;
        this.CardSequencePanel = clp;
        faculty = fp;
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCourseMng = new javax.swing.JButton();
        btnStudentMng = new javax.swing.JButton();
        btnProfileMng = new javax.swing.JButton();
        btnPerformance = new javax.swing.JButton();
        lblFacultyTitle = new javax.swing.JLabel();
        btnTuition = new javax.swing.JButton();

        setForeground(new java.awt.Color(51, 51, 51));

        btnCourseMng.setBackground(new java.awt.Color(102, 153, 255));
        btnCourseMng.setFont(getFont());
        btnCourseMng.setForeground(new java.awt.Color(255, 255, 255));
        btnCourseMng.setText("Course Management");
        btnCourseMng.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCourseMng.setMaximumSize(new java.awt.Dimension(200, 40));
        btnCourseMng.setMinimumSize(new java.awt.Dimension(20, 23));
        btnCourseMng.setPreferredSize(new java.awt.Dimension(240, 30));
        btnCourseMng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCourseMngIdentifyResourceAssetsActionPerformed(evt);
            }
        });

        btnStudentMng.setBackground(new java.awt.Color(102, 153, 255));
        btnStudentMng.setFont(getFont());
        btnStudentMng.setForeground(new java.awt.Color(255, 255, 255));
        btnStudentMng.setText("Student Management");
        btnStudentMng.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnStudentMng.setMaximumSize(new java.awt.Dimension(200, 40));
        btnStudentMng.setMinimumSize(new java.awt.Dimension(20, 20));
        btnStudentMng.setPreferredSize(new java.awt.Dimension(240, 25));
        btnStudentMng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentMngActionPerformed(evt);
            }
        });

        btnProfileMng.setBackground(new java.awt.Color(102, 153, 255));
        btnProfileMng.setFont(getFont());
        btnProfileMng.setForeground(new java.awt.Color(255, 255, 255));
        btnProfileMng.setText("Profile Management");
        btnProfileMng.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnProfileMng.setMaximumSize(new java.awt.Dimension(145, 40));
        btnProfileMng.setMinimumSize(new java.awt.Dimension(20, 20));
        btnProfileMng.setPreferredSize(new java.awt.Dimension(240, 25));
        btnProfileMng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfileMngIdentifyEventsActionPerformed(evt);
            }
        });

        btnPerformance.setBackground(new java.awt.Color(102, 153, 255));
        btnPerformance.setFont(getFont());
        btnPerformance.setForeground(new java.awt.Color(255, 255, 255));
        btnPerformance.setText("Performance Reporting");
        btnPerformance.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPerformance.setMaximumSize(new java.awt.Dimension(200, 40));
        btnPerformance.setMinimumSize(new java.awt.Dimension(20, 20));
        btnPerformance.setPreferredSize(new java.awt.Dimension(240, 25));
        btnPerformance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerformanceActionPerformed(evt);
            }
        });

        lblFacultyTitle.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblFacultyTitle.setText("My Faculty Profile");

        btnTuition.setBackground(new java.awt.Color(102, 153, 255));
        btnTuition.setFont(getFont());
        btnTuition.setForeground(new java.awt.Color(255, 255, 255));
        btnTuition.setText("Tuition/Enrollment Insight");
        btnTuition.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTuition.setMaximumSize(new java.awt.Dimension(145, 40));
        btnTuition.setMinimumSize(new java.awt.Dimension(20, 20));
        btnTuition.setPreferredSize(new java.awt.Dimension(240, 25));
        btnTuition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTuitionIdentifyEventsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFacultyTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnTuition, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                            .addComponent(btnProfileMng, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(btnCourseMng, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnStudentMng, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPerformance, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(551, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblFacultyTitle)
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCourseMng, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnStudentMng, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProfileMng, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPerformance, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(btnTuition, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(139, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCourseMngIdentifyResourceAssetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCourseMngIdentifyResourceAssetsActionPerformed
        // TODO add your handling code here:
        CourseManagementJPanel panel = new CourseManagementJPanel(business, faculty, CardSequencePanel);
        CardSequencePanel.add("CourseManagement", panel);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);

    }//GEN-LAST:event_btnCourseMngIdentifyResourceAssetsActionPerformed

    private void btnStudentMngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentMngActionPerformed
        // TODO add your handling code here:

  
    }//GEN-LAST:event_btnStudentMngActionPerformed

    private void btnProfileMngIdentifyEventsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfileMngIdentifyEventsActionPerformed
        // TODO add your handling code here:
        // CardSequencePanel.removeAll();
        //    IdentifyEventTypes iet= new IdentifyEventTypes(businessunit, CardSequencePanel);

        //    CardSequencePanel.add("IdentifyEventTypes", iet);
        //  ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);

}//GEN-LAST:event_btnProfileMngIdentifyEventsActionPerformed

    private void btnPerformanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerformanceActionPerformed
        // TODO add your handling code here:

}//GEN-LAST:event_btnPerformanceActionPerformed

    private void btnTuitionIdentifyEventsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTuitionIdentifyEventsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTuitionIdentifyEventsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCourseMng;
    private javax.swing.JButton btnPerformance;
    private javax.swing.JButton btnProfileMng;
    private javax.swing.JButton btnStudentMng;
    private javax.swing.JButton btnTuition;
    private javax.swing.JLabel lblFacultyTitle;
    // End of variables declaration//GEN-END:variables

}
