/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package WorkAreas.AdminRole;

import Business.Business;
import Business.Profiles.EmployeeProfile;

import javax.swing.JPanel;
import java.awt.BorderLayout;
import java.awt.FlowLayout;
import javax.swing.JLabel;
import javax.swing.JTabbedPane;
import javax.swing.JButton;

/**
 *
 * @author Ing-Ruei
 */
public class AdminRoleWorkAreaJPanel extends javax.swing.JPanel {

    javax.swing.JPanel CardSequencePanel;
    Business business;
    EmployeeProfile adminProfile;
    JLabel welcomeLabel;
    /**
     * Creates new form UnitRiskWorkArea
     */

    public AdminRoleWorkAreaJPanel(Business b, EmployeeProfile ep, JPanel clp) {

        business = b;
        adminProfile = ep;
        this.CardSequencePanel = clp;
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new BorderLayout());

        // Header Panel for username
        JPanel headerPanel = new JPanel(new FlowLayout(FlowLayout.RIGHT));
                welcomeLabel = new JLabel("Welcome, " + adminProfile.getPerson().getName());
        headerPanel.add(welcomeLabel);
        add(headerPanel, BorderLayout.NORTH);

        // Tabbed Pane
        JTabbedPane tabbedPane = new JTabbedPane();

        // User Management Panel
        JPanel userManagementPanel = new JPanel(new FlowLayout(FlowLayout.CENTER, 20, 20));
        JButton btnRegisterPerson = new JButton("Register Person");
        JButton btnManageUserAccounts = new JButton("Manage User Accounts");
        configureButton(btnRegisterPerson, this::jButton10ActionPerformed);
        configureButton(btnManageUserAccounts, this::jButton4IdentifyResourceAssetsActionPerformed);
        userManagementPanel.add(btnRegisterPerson);
        userManagementPanel.add(btnManageUserAccounts);

        // Profile Management Panel
        JPanel profileManagementPanel = new JPanel(new FlowLayout(FlowLayout.CENTER, 20, 20));
        JButton btnManageFaculty = new JButton("Manage Faculty");
        JButton btnManageStudents = new JButton("Manage Students");
        JButton btnManageRegistrar = new JButton("Manage Registrar");
        configureButton(btnManageFaculty, this::jButton9ActionPerformed);
        configureButton(btnManageStudents, this::jButton8ActionPerformed);
        configureButton(btnManageRegistrar, this::jButton11ActionPerformed);
        profileManagementPanel.add(btnManageFaculty);
        profileManagementPanel.add(btnManageStudents);
        profileManagementPanel.add(btnManageRegistrar);

        // System Panel
        JPanel systemPanel = new JPanel(new FlowLayout(FlowLayout.CENTER, 20, 20));
        JButton btnMyProfile = new JButton("My Profile");
        JButton btnAnalytics = new JButton("University-Level Analytics");
        configureButton(btnMyProfile, this::jButton12IdentifyEventsActionPerformed);
        configureButton(btnAnalytics, this::jButton7IdentifyEventsActionPerformed);
        systemPanel.add(btnMyProfile);
        systemPanel.add(btnAnalytics);

        // Add tabs to tabbed pane
        tabbedPane.addTab("User Management", userManagementPanel);
        tabbedPane.addTab("Profile Management", profileManagementPanel);
        tabbedPane.addTab("System", systemPanel);

        add(tabbedPane, BorderLayout.CENTER);
    }

    public void updateWelcomeLabel() {
        welcomeLabel.setText("Welcome, " + adminProfile.getPerson().getName());
    }

    private void configureButton(javax.swing.JButton button, java.awt.event.ActionListener listener) {
        button.setBackground(new java.awt.Color(102, 153, 255));
        button.setFont(getFont());
        button.setForeground(new java.awt.Color(255, 255, 255));
        button.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        button.setMaximumSize(new java.awt.Dimension(200, 40));
        button.setMinimumSize(new java.awt.Dimension(20, 23));
        button.setPreferredSize(new java.awt.Dimension(240, 30));
        button.addActionListener(listener);
    }
    // </editor-fold>//GEN-END:initComponents

    private void jButton4IdentifyResourceAssetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4IdentifyResourceAssetsActionPerformed
        // TODO add your handling code here:

        ManageUserAccountsJPanel aos = new ManageUserAccountsJPanel(business, CardSequencePanel);

        CardSequencePanel.add("ManageUserAccounts", aos);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);

    }//GEN-LAST:event_jButton4IdentifyResourceAssetsActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:

        PersonRegistrationJPanel aos = new PersonRegistrationJPanel(business, CardSequencePanel);

        CardSequencePanel.add("Manage Persons", aos);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);

    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        ManageUsersByTypeJPanel ms = new ManageUsersByTypeJPanel(business, CardSequencePanel, "Student");
        CardSequencePanel.add("ManageStudent", ms);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        ManageUsersByTypeJPanel mf = new ManageUsersByTypeJPanel(business, CardSequencePanel, "Faculty");
        CardSequencePanel.add("ManageFaculty", mf);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton7IdentifyEventsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7IdentifyEventsActionPerformed
        // TODO add your handling code here:
        AnalyticsDashboardJPanel ap = new AnalyticsDashboardJPanel(business, CardSequencePanel);
        CardSequencePanel.add("analytics", ap);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_jButton7IdentifyEventsActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        ManageUsersByTypeJPanel mr = new ManageUsersByTypeJPanel(business, CardSequencePanel, "Registrar");
        CardSequencePanel.add("ManageRegistrar", mr);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12IdentifyEventsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12IdentifyEventsActionPerformed
        // TODO add your handling code here:
        ProfileManagementJPanel profilePanel = new ProfileManagementJPanel(
        business, 
        adminProfile,
        CardSequencePanel,
        this
        );
        CardSequencePanel.add("adminProfile", profilePanel);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_jButton12IdentifyEventsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}