/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package WorkAreas.StudentRole;
import Business.Business;
import Business.CourseSchedule.CourseLoad;
import Business.Profiles.PaymentRecord;
import Business.Profiles.StudentProfile;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author jim.hsieh
 */
public class FinancialManagementJPanel extends javax.swing.JPanel {
 Business business;
    StudentProfile student;
    JPanel CardSequencePanel;
    /**
     * Creates new form FinancialManagementJPanel
     */
    public FinancialManagementJPanel(Business bz, StudentProfile sp, JPanel panel) {
        initComponents();
        this.business = bz;
    this.student = sp;
    this.CardSequencePanel = panel;
    
    populateFinancialInfo();
    populatePaymentHistory();
    }
    private void populateFinancialInfo() {
        // ========== Account Summary ==========
        
        // 顯示當前餘額（欠款）
        double balance = student.getBalance();
        lblCurrentBalance.setText("Current Balance: $" + String.format("%.2f", balance));
        
        // 如果有欠款，顯示為紅色
        if (balance > 0) {
            lblCurrentBalance.setForeground(new java.awt.Color(255, 0, 0));
        } else {
            lblCurrentBalance.setForeground(new java.awt.Color(0, 128, 0));
        }
        
        // 顯示當前學期
        CourseLoad currentLoad = student.getCurrentCourseLoad();
        if (currentLoad != null) {
            String semester = currentLoad.getSemester();
            lblCurrentSemester.setText("Current Semester: " + semester);
            
            // 計算學期學費
            double tuition = currentLoad.getTuitionFee();
            lblSemesterTuition.setText("Semester Tuition: $" + String.format("%.2f", tuition));
        } else {
            lblCurrentSemester.setText("Current Semester: N/A");
            lblSemesterTuition.setText("Semester Tuition: $0.00");
        }
    }
    
   private void populatePaymentHistory() {
    DefaultTableModel model = (DefaultTableModel) tblPaymentHistory.getModel();
    model.setRowCount(0);
    
    ArrayList<PaymentRecord> history = student.getPaymentHistory();
    
    // 顯示繳費記錄（最新的在前）
    for (int i = history.size() - 1; i >= 0; i--) {
        PaymentRecord record = history.get(i);
        
        // 直接使用 getDate()，因為它已經返回格式化的字符串
        String date = record.getDate();
        String amount = "$" + String.format("%.2f", record.getAmount());
        String semester = record.getSemester();
        
        // 計算該次繳費後的餘額
        double balanceAfter = student.getBalance();
        for (int j = history.size() - 1; j > i; j--) {
            balanceAfter += history.get(j).getAmount();
        }
        String balanceAfterStr = "$" + String.format("%.2f", balanceAfter);
        
        model.addRow(new Object[]{
            date,
            amount,
            semester,
            balanceAfterStr
        });
    }
    
    // 如果沒有繳費記錄
    if (history.isEmpty()) {
        model.addRow(new Object[]{
            "No payment history yet",
            "",
            "",
            ""
        });
    }
    }
    
    private void refreshFinancialInfo() {
        populateFinancialInfo();
        populatePaymentHistory();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        lblFinancialManagement = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jSplitPane2 = new javax.swing.JSplitPane();
        jPanel3 = new javax.swing.JPanel();
        lblAccountSummary = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblCurrentBalance = new javax.swing.JLabel();
        lblCurrentSemester = new javax.swing.JLabel();
        lblSemesterTuition = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel5 = new javax.swing.JPanel();
        lblMakePayment = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        lblPaymentAmount = new javax.swing.JLabel();
        txtPaymentAmount = new javax.swing.JTextField();
        btnMakePayment = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jSplitPane3 = new javax.swing.JSplitPane();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPaymentHistory = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, -1, -1));

        lblFinancialManagement.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        lblFinancialManagement.setText("Financial Management");
        add(lblFinancialManagement, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 250, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jSplitPane2.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        lblAccountSummary.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        lblAccountSummary.setText("Account Summary");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblAccountSummary)
                .addContainerGap(387, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(lblAccountSummary)
                .addGap(40, 40, 40))
        );

        jSplitPane2.setTopComponent(jPanel3);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        lblCurrentBalance.setText("Current Balance:");

        lblCurrentSemester.setText("Current Semester:");

        lblSemesterTuition.setText("Semester Tuition:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblSemesterTuition)
                    .addComponent(lblCurrentSemester)
                    .addComponent(lblCurrentBalance))
                .addContainerGap(434, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblCurrentBalance)
                .addGap(26, 26, 26)
                .addComponent(lblCurrentSemester)
                .addGap(26, 26, 26)
                .addComponent(lblSemesterTuition)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jSplitPane2.setRightComponent(jPanel2);

        jPanel1.add(jSplitPane2, java.awt.BorderLayout.CENTER);

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 610, 240));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        lblMakePayment.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        lblMakePayment.setText("Make Payment");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblMakePayment, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(310, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lblMakePayment)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSplitPane1.setTopComponent(jPanel5);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        lblPaymentAmount.setText("Payment Amount:");

        btnMakePayment.setText("Make Payment");
        btnMakePayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMakePaymentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(lblPaymentAmount)
                .addGap(33, 33, 33)
                .addComponent(txtPaymentAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(btnMakePayment)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPaymentAmount)
                    .addComponent(txtPaymentAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMakePayment))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jSplitPane1.setRightComponent(jPanel6);

        jPanel4.add(jSplitPane1, java.awt.BorderLayout.CENTER);

        add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, 510, 170));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new java.awt.BorderLayout());

        jSplitPane3.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel8.setText("Payment History");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel8)
                .addContainerGap(389, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSplitPane3.setTopComponent(jPanel8);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        tblPaymentHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Amount", "Semester", "Balance After"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPaymentHistory);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                .addContainerGap())
        );

        jSplitPane3.setRightComponent(jPanel9);

        jPanel7.add(jSplitPane3, java.awt.BorderLayout.CENTER);

        add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 600, 600, 280));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.remove(this);
    ((java.awt.CardLayout) CardSequencePanel.getLayout()).previous(CardSequencePanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnMakePaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMakePaymentActionPerformed
        // TODO add your handling code here:
        try {
        // 獲取輸入的金額
        String amountStr = txtPaymentAmount.getText().trim();
        
        if (amountStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Please enter a payment amount.", 
                "Input Required", 
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        double amount = Double.parseDouble(amountStr);
        
        // 驗證金額
        if (amount <= 0) {
            JOptionPane.showMessageDialog(this, 
                "Payment amount must be greater than zero.", 
                "Invalid Amount", 
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        double currentBalance = student.getBalance();
        if (amount > currentBalance) {
            JOptionPane.showMessageDialog(this, 
                "Payment amount cannot exceed current balance ($" + 
                String.format("%.2f", currentBalance) + ").", 
                "Invalid Amount", 
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // 執行繳費
        boolean success = student.payTuition(amount);
        
        if (success) {
            JOptionPane.showMessageDialog(this, 
                "Payment of $" + String.format("%.2f", amount) + " successful!\n" +
                "Remaining balance: $" + String.format("%.2f", student.getBalance()), 
                "Payment Successful", 
                JOptionPane.INFORMATION_MESSAGE);
            
            // 清空輸入框
            txtPaymentAmount.setText("");
            
            // 刷新顯示
            refreshFinancialInfo();
        } else {
            JOptionPane.showMessageDialog(this, 
                "Payment failed. Please try again.", 
                "Payment Failed", 
                JOptionPane.ERROR_MESSAGE);
        }
        
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, 
            "Please enter a valid number.", 
            "Invalid Input", 
            JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnMakePaymentActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnMakePayment;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JSplitPane jSplitPane3;
    private javax.swing.JLabel lblAccountSummary;
    private javax.swing.JLabel lblCurrentBalance;
    private javax.swing.JLabel lblCurrentSemester;
    private javax.swing.JLabel lblFinancialManagement;
    private javax.swing.JLabel lblMakePayment;
    private javax.swing.JLabel lblPaymentAmount;
    private javax.swing.JLabel lblSemesterTuition;
    private javax.swing.JTable tblPaymentHistory;
    private javax.swing.JTextField txtPaymentAmount;
    // End of variables declaration//GEN-END:variables
}
