/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package WorkAreas.RegistrarRole;

import Business.Business;
import Business.CourseCatalog.Course;
import Business.CourseCatalog.CourseCatalog;
import Business.CourseSchedule.CourseOffer;
import Business.CourseSchedule.CourseSchedule;
import Business.Department.Department;
import Business.Directory.FacultyDirectory;
import Business.Directory.StudentDirectory;
import Business.Profiles.FacultyProfile;
import Business.Profiles.StudentProfile;
import java.util.ArrayList;
import java.util.Collection;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author wanyuchiu
 */
public class CreateCourseJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateCourseJPanel
     */
    
    JPanel CardSequencePanel;
    Business business;
    
    public CreateCourseJPanel(Business bz, JPanel jp) {
        
        business = bz;
        this.CardSequencePanel = jp;
        initComponents();
        
        
        Department department = business.getDepartment();
        Collection<CourseSchedule> schedules = department.getAllCourseSchedule();
        
        // 填充學期下拉框
        ComboBoxSemester.removeAllItems();
        if (schedules == null || schedules.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "No semesters available!",
                "Warning",
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        for (CourseSchedule schedule : schedules) {
            ComboBoxSemester.addItem(schedule.getSemester());
        }
        
         // 填充老師下拉框
        FacultyDirectory facultyDirectory = department.getFacultyDirectory();
        ArrayList<FacultyProfile> faculty = facultyDirectory.getFaculty();
        
        for (FacultyProfile facultyProfile : faculty) {
            ComboBoxFaculty.addItem(facultyProfile.getPerson().getName());  
        }
        
        
        
        populateTable();
       
        tblCourse.getSelectionModel().addListSelectionListener(e -> {
        if (!e.getValueIsAdjusting()) {
        loadSelectedRow();
        }
      });
        
        
        
    }
   
    
   /**
     * 填充表格数据
     */
    private void populateTable() {
       
        DefaultTableModel model = (DefaultTableModel) tblCourse.getModel();
        model.setRowCount(0); // 清空表格
        
        Department department = business.getDepartment();
        Collection<CourseSchedule> schedules = department.getAllCourseSchedule();
        
        for (CourseSchedule schedule : schedules) {
            ArrayList<CourseOffer> offers = schedule.getCourseOffers();
            
            for (CourseOffer offer : offers) {
                Course course = offer.getSubjectCourse();
                FacultyProfile fp = offer.getFacultyProfile();
                
                Object[] row = new Object[7];
                row[0] = schedule.getSemester();
                row[1] = course.getCOurseNumber();
                row[2] = course.getCourseName();
                row[3] = course.getCredits();
                row[4] = fp != null ? fp.getPerson().getName() : "TBA"; 
                row[5] = offer.getTotalSeats();
                row[6] = offer.getSchedule() != null ? offer.getSchedule() : "";
                
                model.addRow(row);
            }
        } 
    }
   
    /**
     * 加载选中行的数据到输入框
     */
    private void loadSelectedRow() {
        int selectedRow = tblCourse.getSelectedRow();
        if (selectedRow >= 0) {
            DefaultTableModel model = (DefaultTableModel) tblCourse.getModel();
            
            ComboBoxSemester.setSelectedItem(model.getValueAt(selectedRow, 0).toString());
            txtCourseNumber.setText(model.getValueAt(selectedRow, 1).toString());
            txtCourseName.setText(model.getValueAt(selectedRow, 2).toString());
            txtCredit.setText(model.getValueAt(selectedRow, 3).toString());
            ComboBoxFaculty.setSelectedItem(model.getValueAt(selectedRow, 4).toString());
            txtEnrollmentCapacity.setText(model.getValueAt(selectedRow, 5).toString());
            txtSRoomSchedule.setText(model.getValueAt(selectedRow, 6).toString());
        }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCourseNumber = new javax.swing.JTextField();
        txtCourseName = new javax.swing.JTextField();
        ComboBoxSemester = new javax.swing.JComboBox<>();
        lblCredit = new javax.swing.JLabel();
        lblSemester = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblCourseNumber = new javax.swing.JLabel();
        lblCourseName = new javax.swing.JLabel();
        txtCredit = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCourse = new javax.swing.JTable();
        btnCreate = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtEnrollmentCapacity = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtSRoomSchedule = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        ComboBoxFaculty = new javax.swing.JComboBox<>();

        lblCredit.setText("Credit:");

        lblSemester.setText("Semester :");

        jLabel2.setText("Course Offering Management");

        lblCourseNumber.setText("Course Number :");

        lblCourseName.setText("Course Name :");

        tblCourse.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Semester", "CourseNumber", "CourseName", "Credit", "Faculty", "Enrollment Capacity", "Room/Time Schedule"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCourse);

        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnBack.setText("<<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel3.setText("Faculty:");

        jLabel4.setText("Enrollment Capacity:");

        txtEnrollmentCapacity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnrollmentCapacityActionPerformed(evt);
            }
        });

        jLabel5.setText("Room/Time schedule:");

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBack)
                                .addGap(36, 36, 36)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblSemester)
                                .addGap(50, 50, 50)
                                .addComponent(ComboBoxSemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCredit)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCourseNumber)
                                    .addComponent(lblCourseName)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCredit, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                                    .addComponent(txtCourseName, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                                    .addComponent(txtCourseNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                                    .addComponent(ComboBoxFaculty, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(txtEnrollmentCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(txtSRoomSchedule, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(85, 85, 85)
                                .addComponent(btnCreate)
                                .addGap(34, 34, 34)
                                .addComponent(btnUpdate))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1035, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSemester)
                    .addComponent(ComboBoxSemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCourseNumber)
                    .addComponent(txtCourseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCourseName)
                    .addComponent(txtCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCredit)
                    .addComponent(txtCredit, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(ComboBoxFaculty, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtEnrollmentCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSRoomSchedule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCreate)
                    .addComponent(btnUpdate))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        // 讀取輸入數據
        
        String semester = ComboBoxSemester.getSelectedItem().toString();
        String courseNumber = txtCourseNumber.getText().trim();
        String courseName = txtCourseName.getText().trim();
        String creditStr = txtCredit.getText().trim();
        String facultyName = ComboBoxFaculty.getSelectedItem() != null ? 
                            ComboBoxFaculty.getSelectedItem().toString().trim() : "";
        String capacityStr = txtEnrollmentCapacity.getText().trim();
        String schedule = txtSRoomSchedule.getText().trim();
    
        // 驗證必填字段
        if (courseNumber.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Please Enter Course Number!", 
                "Warning", 
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (courseName.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Please Enter Course Name!", 
                "Warning", 
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (creditStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Please enter Credit Amount!", 
                "Input Error", 
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (capacityStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Please enter Enrollment Capacity!", 
                "Input Error", 
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (facultyName.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Please select a Faculty!", 
                "Input Error", 
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // 驗證數字格式
        int credits;
        int capacity;
        try {
            credits = Integer.parseInt(creditStr);
            capacity = Integer.parseInt(capacityStr);
            
            if (credits <= 0 || capacity <= 0) {
                throw new NumberFormatException();
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, 
                "Credits and Capacity must be positive numbers!", 
                "Input Error", 
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        Department department = business.getDepartment();
        
        // 檢查課程是否已存在於該學期
        CourseSchedule courseSchedule = department.getCourseSchedule(semester);
        if (courseSchedule == null) {
            JOptionPane.showMessageDialog(this, 
                "Course schedule not found for semester: " + semester, 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        CourseOffer existingOffer = courseSchedule.getCourseOfferByNumber(courseNumber);
        if (existingOffer != null) {
            JOptionPane.showMessageDialog(this, 
                "Course already exists in this semester!\nSemester: " + semester + 
                "\nCourse Number: " + courseNumber, 
                "Duplicate Course", 
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // 在CourseCatalog中查找或創建課程
        CourseCatalog catalog = department.getCourseCatalog();
        Course course = catalog.getCourseByNumber(courseNumber);
        
        if (course == null) {
            // 如果課程不存在於catalog中，創建新課程
            course = catalog.newCourse(courseName, courseNumber, credits);
        } else {
            // 如果課程已存在，更新課程信息
            course.setCourseName(courseName);
        }
        
        // 創建CourseOffer
        CourseOffer newOffer = courseSchedule.newCourseOffer(courseNumber);
        if (newOffer == null) {
            JOptionPane.showMessageDialog(this, 
                "Failed to create course offer!", 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // 設置課程容量和時間表
        newOffer.generateSeats(capacity);
        if (schedule != null && !schedule.isEmpty()) {
            newOffer.setSchedule(schedule);
        }
        
        // 分配Faculty
        FacultyDirectory facultyDirectory = department.getFacultyDirectory();
        FacultyProfile selectedFaculty = null;
        
        for (FacultyProfile fp : facultyDirectory.getFaculty()) {
            if (fp.getPerson().getName().equals(facultyName)) {
                selectedFaculty = fp;
                break;
            }
        }
        
        if (selectedFaculty != null) {
            newOffer.AssignAsTeacher(selectedFaculty);
        }
        
        // 刷新表格
        populateTable();
        
        // 清空輸入框
        txtCourseNumber.setText("");
        txtCourseName.setText("");
        txtCredit.setText("");
        ComboBoxFaculty.setSelectedIndex(0);
        txtEnrollmentCapacity.setText("");
        txtSRoomSchedule.setText("");
        
        // 顯示成功消息
        JOptionPane.showMessageDialog(this, 
            "Course Created Successfully!\nFaculty can now manage this course.", 
            "Success", 
            JOptionPane.INFORMATION_MESSAGE);    
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).previous(CardSequencePanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtEnrollmentCapacityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnrollmentCapacityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnrollmentCapacityActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        // 檢查是否選擇了表格行
        int selectedRow = tblCourse.getSelectedRow();
        
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, 
                "Please select a course from the table first!", 
                "No Selection", 
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // 讀取輸入框的數據
        String semester = ComboBoxSemester.getSelectedItem().toString().trim();
        String courseNumber = txtCourseNumber.getText().trim();
        String courseName = txtCourseName.getText().trim();
        String creditStr = txtCredit.getText().trim();
        String facultyName = ComboBoxFaculty.getSelectedItem() != null ? 
                            ComboBoxFaculty.getSelectedItem().toString().trim() : "";
        String capacityStr = txtEnrollmentCapacity.getText().trim();
        String schedule = txtSRoomSchedule.getText().trim();
        
        // 驗證必填字段
        if (courseNumber.isEmpty() || courseName.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Please enter Course Number and Course Name!", 
                "Input Error", 
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (creditStr.isEmpty() || capacityStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Please enter Credit and Enrollment Capacity!", 
                "Input Error", 
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // 驗證數字格式
        int credits;
        int capacity;
        try {
            credits = Integer.parseInt(creditStr);
            capacity = Integer.parseInt(capacityStr);
            
            if (credits <= 0 || capacity <= 0) {
                throw new NumberFormatException();
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, 
                "Credits and Capacity must be positive numbers!", 
                "Input Error", 
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        Department department = business.getDepartment();
        
        // 獲取原始課程號碼（從表格選中行）
        String originalCourseNumber = tblCourse.getValueAt(selectedRow, 1).toString();
        String originalSemester = tblCourse.getValueAt(selectedRow, 0).toString();
        
        // 獲取CourseSchedule和CourseOffer
        CourseSchedule courseSchedule = department.getCourseSchedule(originalSemester);
        if (courseSchedule == null) {
            JOptionPane.showMessageDialog(this, 
                "Course schedule not found!", 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        CourseOffer courseOffer = courseSchedule.getCourseOfferByNumber(originalCourseNumber);
        if (courseOffer == null) {
            JOptionPane.showMessageDialog(this, 
                "Course offer not found!", 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // 更新Course信息
        Course course = courseOffer.getSubjectCourse();
        course.setCourseName(courseName);
        
        // 更新CourseOffer信息
        if (schedule != null && !schedule.isEmpty()) {
            courseOffer.setSchedule(schedule);
        }
        
        // 更新容量
        int currentEnrolled = courseOffer.getTotalRegistedStudent();
        if (capacity < currentEnrolled) {
            JOptionPane.showMessageDialog(this, 
                "New capacity (" + capacity + ") cannot be less than\n" +
                "currently enrolled students (" + currentEnrolled + ")!", 
                "Invalid Capacity", 
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        boolean capacityUpdated = courseOffer.updateCapacity(capacity);
        if (!capacityUpdated) {
            JOptionPane.showMessageDialog(this, 
                "Failed to update capacity!", 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // 更新Faculty分配
        if (!facultyName.isEmpty()) {
            FacultyDirectory facultyDirectory = department.getFacultyDirectory();
            FacultyProfile selectedFaculty = null;
            
            for (FacultyProfile fp : facultyDirectory.getFaculty()) {
                if (fp.getPerson().getName().equals(facultyName)) {
                    selectedFaculty = fp;
                    break;
                }
            }
            
            if (selectedFaculty != null) {
                courseOffer.AssignAsTeacher(selectedFaculty);
            }
        }
        
        // 刷新表格
        populateTable();
        
        // 清空輸入框
        txtCourseNumber.setText("");
        txtCourseName.setText("");
        txtCredit.setText("");
        ComboBoxFaculty.setSelectedIndex(0);
        txtEnrollmentCapacity.setText("");
        txtSRoomSchedule.setText("");
        
        // 顯示成功消息
        JOptionPane.showMessageDialog(this, 
            "Course Updated Successfully!", 
            "Success", 
            JOptionPane.INFORMATION_MESSAGE);                                         

                                             
    }//GEN-LAST:event_btnUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxFaculty;
    private javax.swing.JComboBox<String> ComboBoxSemester;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCourseName;
    private javax.swing.JLabel lblCourseNumber;
    private javax.swing.JLabel lblCredit;
    private javax.swing.JLabel lblSemester;
    private javax.swing.JTable tblCourse;
    private javax.swing.JTextField txtCourseName;
    private javax.swing.JTextField txtCourseNumber;
    private javax.swing.JTextField txtCredit;
    private javax.swing.JTextField txtEnrollmentCapacity;
    private javax.swing.JTextField txtSRoomSchedule;
    // End of variables declaration//GEN-END:variables
}
