/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package WorkAreas.RegistrarRole;

import Business.Business;
import Business.CourseCatalog.Course;
import Business.CourseCatalog.CourseCatalog;
import Business.CourseSchedule.CourseOffer;
import Business.CourseSchedule.CourseSchedule;
import Business.Department.Department;
import Business.Profiles.FacultyProfile;
import java.util.ArrayList;
import java.util.Collection;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author wanyuchiu
 */
public class CreateCourseJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateCourseJPanel
     */
    
    JPanel CardSequencePanel;
    Business business;
    
    public CreateCourseJPanel(Business bz, JPanel jp) {
        
        business = bz;
        this.CardSequencePanel = jp;
        initComponents();
        
        populateTable();
       
        tblCourse.getSelectionModel().addListSelectionListener(e -> {
        if (!e.getValueIsAdjusting()) {
        loadSelectedRow();
        }
      });
        
    }
    
   /**
     * 填充表格数据
     */
    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblCourse.getModel();
        model.setRowCount(0);
    
        Department department = business.getDepartment();
        Collection<CourseSchedule> schedules = department.getAllCourseSchedule();
        
        for (CourseSchedule schedule : schedules) {
            String semester = schedule.getTerm();
            ArrayList<CourseOffer> offers = schedule.getCourseOffers();
          
                
            for (CourseOffer offer : offers) {
                Course course = offer.getSubjectCourse();
                FacultyProfile fp = offer.getFacultyProfile();
                
                
                Object[] row = new Object[7];
                row[0] = semester;
                row[1] = course.getCOurseNumber();
                row[2] = course.getCourseName();
                row[3] = course.getCredits();
                row[4] = fp.getFacultyName(); 
                row[5] = offer.getTotalSeats();
                row[6] = offer.getSchedule();
                
                model.addRow(row);
            }
        }
    }
   
    /**
     * 加载选中行的数据到输入框
     */
    private void loadSelectedRow() {
        int selectedRow = tblCourse.getSelectedRow();
        if (selectedRow >= 0) {
            DefaultTableModel model = (DefaultTableModel) tblCourse.getModel();
            
            ComboBoxSemester.setSelectedItem(model.getValueAt(selectedRow, 0).toString());
            txtCourseNumber.setText(model.getValueAt(selectedRow, 1).toString());
            txtCourseName.setText(model.getValueAt(selectedRow, 2).toString());
            txtCredit.setText(model.getValueAt(selectedRow, 3).toString());
            txtFaculty.setText(model.getValueAt(selectedRow, 4).toString());
            txtEnrollmentCapacity.setText(model.getValueAt(selectedRow, 5).toString());
            txtSRoomSchedule.setText(model.getValueAt(selectedRow, 6).toString());
        }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCourseNumber = new javax.swing.JTextField();
        txtCourseName = new javax.swing.JTextField();
        ComboBoxSemester = new javax.swing.JComboBox<>();
        lblCredit = new javax.swing.JLabel();
        lblSemester = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblCourseNumber = new javax.swing.JLabel();
        lblCourseName = new javax.swing.JLabel();
        txtCredit = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCourse = new javax.swing.JTable();
        btnCreate = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtFaculty = new javax.swing.JTextField();
        txtEnrollmentCapacity = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtSRoomSchedule = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();

        ComboBoxSemester.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fall2023", "Spring2024", "Fall2024", "Spring2025", " " }));

        lblCredit.setText("Credit:");

        lblSemester.setText("Semester :");

        jLabel2.setText("Course Offering Management");

        lblCourseNumber.setText("Course Number :");

        lblCourseName.setText("Course Name :");

        tblCourse.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Semester", "CourseNumber", "CourseName", "Credit", "Faculty", "Enrollment Capacity", "Room/Time Schedule"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCourse);

        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnBack.setText("<<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel3.setText("Faculty:");

        jLabel4.setText("Enrollment Capacity:");

        txtEnrollmentCapacity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnrollmentCapacityActionPerformed(evt);
            }
        });

        jLabel5.setText("Room/Time schedule:");

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBack)
                                .addGap(36, 36, 36)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblSemester)
                                .addGap(50, 50, 50)
                                .addComponent(ComboBoxSemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCredit)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCourseNumber)
                                    .addComponent(lblCourseName)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCredit, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFaculty, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCourseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(txtEnrollmentCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(txtSRoomSchedule, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(85, 85, 85)
                                .addComponent(btnCreate)
                                .addGap(34, 34, 34)
                                .addComponent(btnUpdate))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1024, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSemester)
                    .addComponent(ComboBoxSemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCourseNumber)
                    .addComponent(txtCourseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCourseName)
                    .addComponent(txtCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCredit)
                    .addComponent(txtCredit, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFaculty, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtEnrollmentCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSRoomSchedule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCreate)
                    .addComponent(btnUpdate))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(116, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        String semester = ComboBoxSemester.getSelectedItem().toString();
        String courseNumber = txtCourseNumber.getText();
        String courseName = txtCourseName.getText();
        String credit = txtCredit.getText();
        String faculty = txtFaculty.getText();
        String capacity = txtEnrollmentCapacity.getText();
        String schedule = txtSRoomSchedule.getText();
    
        // 2. 验证必填字段
        if (courseNumber.isEmpty()) {
        JOptionPane.showMessageDialog(this, 
            "Please Enter Course Number！", 
            "Warnning", 
            JOptionPane.WARNING_MESSAGE);
        return;
        }
        
        
        
        // 3. 创建新行数据
        DefaultTableModel model = (DefaultTableModel) tblCourse.getModel();
         for (int i = 0; i < model.getRowCount(); i++) {
            String existingSemester = model.getValueAt(i, 0).toString();
            String existingCourseNumber = model.getValueAt(i, 1).toString();
            
            if (existingSemester.equals(semester) && existingCourseNumber.equals(courseNumber)) {
                JOptionPane.showMessageDialog(this, 
                    "CourseNumber Already Exist！\nSemester: " + semester + "\nCourseNumber: " + courseNumber, 
                    "Duplicate CourseNumber", 
                    JOptionPane.WARNING_MESSAGE);
                return;
            }
        }
         
        if (courseName.isEmpty()) {
        JOptionPane.showMessageDialog(this, 
            "Please Enter Course Name！", 
            "Warnning", 
            JOptionPane.WARNING_MESSAGE);
        return;
        }
         if (credit.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Please enter Credit Amount!", 
                "Input Error", 
                JOptionPane.ERROR_MESSAGE);
            return;
        }
         if (capacity.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Please enter Enrollment Capacity!", 
                "Input Error", 
                JOptionPane.ERROR_MESSAGE);
            return;
        }
    
    
        Object[] row = new Object[7];
        row[0] = semester;
        row[1] = courseNumber;
        row[2] = courseName;
        row[3] = credit.isEmpty() ? "" : credit;
        row[4] = faculty.isEmpty() ? "" : faculty;
        row[5] = capacity.isEmpty() ? "" : capacity;
        row[6] = schedule.isEmpty() ? "" : schedule;
    
    // 4. 添加到表格
        model.addRow(row);
    
        txtCourseNumber.setText("");
        txtCourseName.setText("");
        txtCredit.setText("");
        txtFaculty.setText("");
        txtEnrollmentCapacity.setText("");
        txtSRoomSchedule.setText("");
    
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).previous(CardSequencePanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtEnrollmentCapacityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnrollmentCapacityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnrollmentCapacityActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        
         // 1. 检查是否选择了表格行
        int selectedRow = tblCourse.getSelectedRow();
        
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, 
                "Please select a course from the table first!", 
                "No Selection", 
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // 2. 读取输入框的数据
        String semester = ComboBoxSemester.getSelectedItem().toString().trim();
        String courseNumber = txtCourseNumber.getText().trim();
        String courseName = txtCourseName.getText().trim();
        String credit = txtCredit.getText().trim();
        String faculty = txtFaculty.getText().trim();
        String capacity = txtEnrollmentCapacity.getText().trim();
        String schedule = txtSRoomSchedule.getText().trim();
        
        // 3. 验证必填字段
        if (courseNumber.isEmpty() || courseName.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Please enter Course Number and Course Name!", 
                "Input Error", 
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (capacity.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Please enter Enrollment Capacity!", 
                "Input Error", 
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // 4. 更新表格中选中行的数据
        DefaultTableModel model = (DefaultTableModel) tblCourse.getModel();
        
        model.setValueAt(semester, selectedRow, 0);
        model.setValueAt(courseNumber, selectedRow, 1);
        model.setValueAt(courseName, selectedRow, 2);
        model.setValueAt(credit.isEmpty() ? "" : credit, selectedRow, 3);
        model.setValueAt(faculty.isEmpty() ? "" : faculty, selectedRow, 4);
        model.setValueAt(capacity.isEmpty() ? "" : capacity, selectedRow, 5);
        model.setValueAt(schedule.isEmpty() ? "" : schedule, selectedRow, 6);
        
        // 5. 清空输入框
        txtCourseNumber.setText("");
        txtCourseName.setText("");
        txtCredit.setText("");
        txtFaculty.setText("");
        txtEnrollmentCapacity.setText("");
        txtSRoomSchedule.setText("");
    
        
        // 6. 显示成功消息
        JOptionPane.showMessageDialog(this, 
            "Course Updated Successfully!", 
            "Success", 
            JOptionPane.INFORMATION_MESSAGE);
    //GEN-LAST:event_btnUpdateActionPerformed
    }//GEN-LAST:event_btnUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxSemester;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCourseName;
    private javax.swing.JLabel lblCourseNumber;
    private javax.swing.JLabel lblCredit;
    private javax.swing.JLabel lblSemester;
    private javax.swing.JTable tblCourse;
    private javax.swing.JTextField txtCourseName;
    private javax.swing.JTextField txtCourseNumber;
    private javax.swing.JTextField txtCredit;
    private javax.swing.JTextField txtEnrollmentCapacity;
    private javax.swing.JTextField txtFaculty;
    private javax.swing.JTextField txtSRoomSchedule;
    // End of variables declaration//GEN-END:variables
}
