/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package WorkAreas.RegistrarRole;

import Business.Business;
import Business.Person.Person;
import Business.Profiles.RegistrarProfile;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author wanyuchiu
 */

public class ManageOwnProfileJPanel extends javax.swing.JPanel {

    JPanel CardSequencePanel;
    Business business;
    RegistrarProfile registrar;
    /**
     * Creates new form ManageOwnProfileJPanel
     */
    public ManageOwnProfileJPanel(Business bz, JPanel jp,RegistrarProfile rp) {
         business = bz;
         this.CardSequencePanel = jp;
         this.registrar = rp;
         
         initComponents();
          // load Registrar data
         loadRegistrarProfile();
        
        // set Name to read only
         txtRName.setEditable(false);
    }
  
     
    private void loadRegistrarProfile() {
        if (registrar == null || registrar.getPerson() == null) {
            JOptionPane.showMessageDialog(this,
                "Registrar profile not found!",
                "Error",
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        Person person = registrar.getPerson();
        
        //get exisiting data
        txtRName.setText(person.getName());
        txtEmail.setText(registrar.getEmail());
        txtPhone.setText(registrar.getPhone());
        txtOffice.setText(registrar.getOffice());
        txtOfficeHours.setText(registrar.getOfficeHours());
        
      
        //updateTable();
    }
           
        
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtRName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtOffice = new javax.swing.JTextField();
        txtOfficeHours = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();

        jLabel1.setText("Email");

        jLabel2.setText("Phone:");

        jLabel3.setText("Name:");

        txtRName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRNameActionPerformed(evt);
            }
        });

        jLabel4.setText("Office:");

        jLabel5.setText("Office Hour:");

        txtOfficeHours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOfficeHoursActionPerformed(evt);
            }
        });

        jLabel6.setText("OWN Profile");

        btnBack.setText("<<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtRName)
                            .addComponent(txtEmail)
                            .addComponent(txtPhone)
                            .addComponent(txtOffice)
                            .addComponent(txtOfficeHours, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(76, 76, 76)
                        .addComponent(btnSave)
                        .addGap(45, 45, 45)
                        .addComponent(btnReset))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)))
                .addContainerGap(238, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtRName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addComponent(jLabel4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(btnBack))
                        .addGap(170, 170, 170)
                        .addComponent(txtOffice, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtOfficeHours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSave)
                        .addComponent(btnReset)))
                .addContainerGap(365, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtRNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRNameActionPerformed

    private void txtOfficeHoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOfficeHoursActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOfficeHoursActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).previous(CardSequencePanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here: 
        //Step 1: collect text from the field
        String name = txtRName.getText().trim();
        String email = txtEmail.getText().trim();
        String phone = txtPhone.getText().trim();
        String office = txtOffice.getText().trim();
        String officeHours = txtOfficeHours.getText().trim();
        
        // Step2 : verify 
        if (name.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Name cannot be empty!",
                "Validation Error",
                JOptionPane.ERROR_MESSAGE);
            txtRName.requestFocus();
            return;
        }
        
        if (email.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Email cannot be empty!",
                "Validation Error",
                JOptionPane.ERROR_MESSAGE);
            txtEmail.requestFocus();
            return;
        }
        
        // Step3 : Email type in check
        if (!email.contains("@") || !email.contains(".")) {
            JOptionPane.showMessageDialog(this,
                "Please enter a valid email address!\n" +
                "Example: registrar@university.edu",
                "Validation Error",
                JOptionPane.ERROR_MESSAGE);
            txtEmail.requestFocus();
            return;
        }
        
        //  Step4 : PhoneNumber type in check
        if (!phone.isEmpty() && !phone.matches("[0-9-()+ ]+")) {
            JOptionPane.showMessageDialog(this,
                "Please enter a valid phone number!\n" +
                "Example: 617-555-0100 or (617) 555-0100",
                "Validation Error",
                JOptionPane.ERROR_MESSAGE);
            txtPhone.requestFocus();
            return;
        }
        
        try {
            // 
            registrar.setEmail(email);
            registrar.setPhone(phone);
            registrar.setOffice(office);
            registrar.setOfficeHours(officeHours);
            
            
            
            JOptionPane.showMessageDialog(this,
                "Profile saved successfully!\n\n" +
                "Name: " + name + "\n" +
                "Email: " + email + "\n" +
                "Phone: " + phone + "\n" +
                "Office: " + office + "\n" +
                "Office Hours: " + officeHours,
                "Success",
                JOptionPane.INFORMATION_MESSAGE);
            
            System.out.println("Profile saved:");
            System.out.println("  Email: " + registrar.getEmail());
            System.out.println("  Phone: " + registrar.getPhone());
            System.out.println("  Office: " + registrar.getOffice());
            System.out.println("  Office Hours: " + registrar.getOfficeHours());
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "Failed to save profile: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        
        
        //retrace previous data 
        int confirm = JOptionPane.showConfirmDialog(this,
            "This will discard any unsaved changes.\n" +"Are you sure you want to refresh?",
            "Confirm Refresh",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE);
        
        if (confirm == JOptionPane.YES_OPTION) {
            loadRegistrarProfile();
            JOptionPane.showMessageDialog(this,
                "Profile refreshed from saved data.",
                "Refreshed",
                JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_btnResetActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtOffice;
    private javax.swing.JTextField txtOfficeHours;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtRName;
    // End of variables declaration//GEN-END:variables
}
