/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package WorkAreas.RegistrarRole;

import Business.Business;
import Business.Department.Department;
import Business.Directory.StudentDirectory;
import Business.Profiles.StudentProfile;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author wanyuchiu
 */
public class TuitionReconciliationJPanel extends javax.swing.JPanel {
    
     Business business;
     JPanel CardSequencePanel;
    /**
     * Creates new form TuitionJPanel
     */
    public TuitionReconciliationJPanel(Business bz,JPanel jp) {
        business = bz; 
        this.CardSequencePanel = jp;
        
        initComponents();
        populateTable();
        
    }
    int a = 0;
    public int AA(){
         int b = a + 100;
         return b;
    }
    public int BB(){
         return a;
    }
    
    
    
    private void populateTable() {
        
        DefaultTableModel model = (DefaultTableModel) tblTuitionStatus.getModel();
        model.setRowCount(0); // 清空表格
        
        
        
        Department department = business.getDepartment();
        //System.out.println("Department: " + department);
        StudentDirectory studentDirectory = department.getStudentDirectory(); //return StudentDirectory
        //System.out.println("CourseCatalog: " + courseCatalog);
        ArrayList<StudentProfile> student = studentDirectory.getStudent();
        
        double totalTuitionCollected = 0;
        double totalBalance = 0;
        for (StudentProfile studentProfile : student) {
            
            String Semester = studentProfile.getCurrentCourseLoad().getSemester();
            String ID = studentProfile.getPerson().getPersonId();
            String name = studentProfile.getPerson().getName();
            
            double balance = studentProfile.getBalance();
            // 計算已支付金額
            totalBalance += balance;    
            
            double tuition = studentProfile.getCurrentCourseLoad().getTuitionFee();
             //CourseLoad
            
            double paidAmount = tuition - balance;
            //boolean status = studentProfile.payTuition(0);
            
            
            totalTuitionCollected = totalTuitionCollected + tuition;
            
            
              // 判斷支付狀態
                String status = (balance <= 0) ? "Paid" : "Unpaid";
                
             // 添加到表格
                Object[] row = new Object[7];
                row[0] = Semester;
                row[1] = ID;
                row[2] = name;
                row[3] = tuition;
                row[4] = paidAmount;
                row[5] = balance;
                row[6] = status;
                
                model.addRow(row);
                
          
        }
        refreshTable(totalTuitionCollected,totalBalance);
        
    }
    
        


    
    
    private void refreshTable(Double tui, Double t) {
        
        DefaultTableModel model = (DefaultTableModel) tblTuitionPaid.getModel();
        model.setRowCount(0); // 清空表格
       
                
             // 添加到表格
                Object[] row = new Object[2];
                row[0] = tui;
                row[1] = t;
                
                model.addRow(row);
                
          
    }
    
          
        

    
        
   
//         
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblTuitionStatus = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTuitionPaid = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        tblTuitionStatus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Semester", "Student ID", "Student Name", "Tuition", "Paid", "Balance", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblTuitionStatus);

        tblTuitionPaid.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Total Tuition collected", "UnPaid"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblTuitionPaid);

        jLabel1.setText("Tuition & Financial Reconciliation");

        jLabel2.setText("Financial Reconciliation");

        jLabel3.setText("Tuition Reconciliation");

        btnBack.setText("<<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel1)
                                .addComponent(btnBack))
                            .addGap(902, 902, 902)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).previous(CardSequencePanel);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblTuitionPaid;
    private javax.swing.JTable tblTuitionStatus;
    // End of variables declaration//GEN-END:variables
}
